import streamlit as st
from processpiper.text2diagram import render

def main():
    st.title("Interactive Process Diagram Generator")

    input_syntax = """
title: Interactive Process Diagram
colourtheme: DEFAULT
"""

    lane_count = st.number_input("Enter the number of lanes:", min_value=1, step=1, value=1)
    for i in range(lane_count):
        lane_name = st.text_input(f"Enter the name of Lane {i + 1}:")
        input_syntax += f"    lane: {lane_name}\n"

    pool_name = st.text_input("Enter the name of the Pool:")
    input_syntax += f"pool: {pool_name}\n"

    st.write("Enter connections (source -> target). Type 'done' to finish.")
    while True:
        source = st.text_input("Enter the source component:")
        if source.lower() == 'done':
            break
        target = st.text_input(f"Enter the target component for '{source}':")
        input_syntax += f"{source}->{target}\n"

    input_syntax += "\nfooter: Generated by ProcessPiper"

    render(input_syntax, "interactive_process_map.png")

if __name__ == "__main__":
    main()
