import streamlit as st
from processpiper.text2diagram import render

def main():
    st.title("Interactive Process Diagram Generator")

    # User input for process diagram details
    title = st.text_input("Enter diagram title:", "Sample Test Process", key="diagram_title")
    color_theme = st.selectbox("Select color theme:", ["GREENTURTLE", "BLUEMOUNTAIN", "DEFAULT"], key="color_theme")

    input_syntax = f"""
title: {title}
colourtheme: {color_theme}
    lane: End User
        (start) as start
        [Enter Keyword] as enter_keyword
        (end) as end
    pool: System Search
        lane: Database System
            [Login] as login
            [Search Records] as search_records
            <Result Found?> as result_found
            [Display Result] as display_result
            [Logout] as logout
        lane: Log System
            [Log Error] as log_error

"""

    st.write("Enter connections (source -> target). Type 'done' to finish.")
    connection_count = 0
    while True:
        connection_count += 1
        source = st.text_input(f"Enter the source component for connection {connection_count}:", key=f"source_{connection_count}")
        if source.lower() == 'done':
            break
        target = st.text_input(f"Enter the target component for connection {connection_count}:", key=f"target_{connection_count}")
        input_syntax += f"{source}->{target}\n"

    input_syntax += "\nfooter: Generated by ProcessPiper"

    # Display the generated process diagram
    st.subheader("Generated Process Diagram:")
    render(input_syntax, "my_diagram.png")
    st.image("my_diagram.png", use_column_width=True)

if __name__ == "__main__":
    main()
